---
title: "lionfishanalysis_kb_v6"
author: "Kim Bourne"
date: "May 15, 2018"
output: pdf_document
fontsize: 12pt
---

```{r}
###### read in data #######
data_all <- read.csv('data/lionfishdata.csv')
counts <- data.frame(N_chromis = data_all$Numberchromisconsumed, N_goby = data_all$Numbergobyconsumed,N_wrasse = data_all$Numberwrasseconsumed)
```

```{r}
####### Use zCompositions to replace zeros using bayesian multiplicative methods #######
library('zCompositions')
c_tot <- counts$N_chromis + counts$N_wrasse + counts$N_goby

p <- cbind(counts$N_chromis/c_tot,counts$N_goby/c_tot,counts$N_wrasse/c_tot) # proportions of each species based on total eaten
rep_p <- cmultRepl(counts,method = "SQ") # proportions data with zeros replaced
rep_count<-rep_p*c_tot
colnames(p) <- c("P_chromis","P_goby","P_wrasse")
colnames(rep_p) <- c("P_chromis","P_goby","P_wrasse")
apply(counts,1,sum)
apply(rep_count,1,sum) 
apply(rep_p,1,sum) 

rep_biomass <- rep_count*matrix(rep(c(0.641,0.129,0.655),each = nrow(rep_count)),nrow = nrow(rep_count))
rep_bioprops <- rep_biomass/apply(rep_biomass,FUN = sum,MARGIN = 1)
colnames(rep_biomass) <- c("chromis","goby","wrasse")
colnames(rep_bioprops) <- c("P_chromis","P_goby","P_wrasse")
```

```{r}
# M: function fsbp2ilr: function to transform partitions (SBP) to ilr-basis
##
fsbp2ilr<-function(s){
  # given a vector (or a set of vectors) of a SBP formed by 0,+1,-1 
  # returns the ilr-vector (or set of) or balance
  # author: Martin (2015)
  
  bal=s
  
  if(is.null(dim(s))) 
  {
       
    den<-sum(bal==-1)
    num<-sum(bal==1)  
    bal[s==1]<-sqrt(den/((den+num)*num))
    bal[s==-1]<--sqrt(num/((den+num)*den))
    
    
  }
  else
  {
    numsbp=dim(s)[1]
    for (f in 1:numsbp) {
      den<-sum(bal[f,]==-1)
      num<-sum(bal[f,]==1)  
      bal[f,bal[f,]==1]<-sqrt(den/((den+num)*num))
      bal[f,bal[f,]==-1]<--sqrt(num/((den+num)*den))
      
    }
    
  }
  
  return(bal)
}

tU3=as.matrix(fsbp2ilr(rbind(c(1,-1,1),c(1,0,-1))))
U3=t(tU3)

ilr_rep_biop <-log(as.matrix(rep_bioprops))%*%U3 # compute ilr-coordinates
library("compositions")
colnames(ilr_rep_biop)<-c('CW_G','C_W')

rep_bioprops2 <- exp(ilr_rep_biop%*%tU3)/apply(exp(ilr_rep_biop%*%tU3),1,sum)
```


models for predicting the proportions of each fish eaten 

```{r}
###### regress ilr variables on body condition #######
formula <- as.formula(cbind(CW_G,C_W) ~ BodyCondition)

(model1 <- lm(formula,data = cbind(ilr_rep_biop,data_all)))
intercept_ilr <- model1$coefficients[1,]
slope_ilr <- model1$coefficients[2,]
predictedilr <- predict(model1)
predicted <- exp(predictedilr%*%tU3)/apply(exp(predictedilr%*%tU3),1,sum)

###### determine the inverse transformed linear regression  #######
slope <- exp(model1$coefficients[2,]%*%tU3)/sum(exp(model1$coefficients[2,]%*%tU3))
intercept <- exp(model1$coefficients[1,]%*%tU3)/sum(exp(model1$coefficients[1,]%*%tU3))
x <- data.frame(BodyCondition = seq(0.01,0.018,by = 0.001))
y_ilr <- predict(model1,newdata = x)
y <- exp(y_ilr%*%tU3)/apply(exp(y_ilr%*%tU3),1,sum)

plot(data_all$BodyCondition,predicted[,1],ylim = c(0,1), xlab = 'Body Condition',ylab = 'Percent Diet Comprised by Species',pch = 15, frame.plot = FALSE)
points(data_all$BodyCondition,predicted[,2],col='blue', pch = 18)
points(data_all$BodyCondition,predicted[,3],col='green', pch = 17)
legend(x='topright',legend = c('Chromis','Goby','Wrasse'),col = c('black','green','blue'),pch = c(15,18,17))

###### plot inverse ilr transformed linear regressions  #######
#png("model_predictions.png",width = 600, height = 400)
plot(x$BodyCondition,y[,1],xlim = c(0.011,0.018),ylim = c(0,1), xlab = 'Body Condition',ylab = 'Percent Diet Comprised by Species',type="l", frame.plot = FALSE, lwd = 2,cex.axis = 1.5,cex.lab = 1.5)
lines(x$BodyCondition,y[,2],col='blue', lty = 2, lwd = 2)
lines(x$BodyCondition,y[,3],col='red', lty = 4, lwd = 2)
points(data_all$BodyCondition,p[,1],pch = 1,cex = 1.5)
points(data_all$BodyCondition,p[,2],pch = 3,col = 'blue',cex = 1.5)
points(data_all$BodyCondition,p[,3],pch = 4,col = 'red',cex = 1.5)
#
legend(x='topright',legend = c('Chromis','Goby','Wrasse'),col = c('black','red','blue'),lty = c(1,2,4),lwd = 2,cex = 1.5)
#dev.off()
```


